@Library('my-shared-library') _
def terraformCI = new org.template.terraform()
node {
   // withAWS(roleAccount: '686255949108', role: 'JenkinsAssumeRole', roleSessionName: 'jenkins-session') {
    withCredentials([aws(credentialsId: 'vishal-aws-creds', accessKeyVariable: 'AWS_ACCESS_KEY_ID', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {   
        script {
            def url = 'https://github.com/7828143960/shreya_private.git'
            def creds = 'shreya-github-id'
            def branch  = "terraform-sl"
            def rootPath = "Jenkinsfile"
            def childPath = "terraform"
            terraformCI.call(url, creds, branch, rootPath, childPath)
        }
    }
}
