---
- name: Install MySQL dependencies on Ubuntu
  apt:
    name:
      - libaio1
      - libnuma1
    state: present
  become: yes

- name: Remove MySQL setup files
  ansible.builtin.file:
    path: /tmp/mysql-8.2.0-linux-glibc2.28-x86_64.tar.xz
    state: absent
